[project]
name = "kafka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "quixstreams>=3.19.0",
    "streamlit>=1.46.1",
]
